//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package offerprice.rq;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomainSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="DomainSimpleType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="AirlineProfile"/>
 *     <enumeration value="OrderManagement"/>
 *     <enumeration value="PaymentTicketing"/>
 *     <enumeration value="Shopping"/>
 *     <enumeration value="Utility"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "DomainSimpleType")
@XmlEnum
public enum DomainSimpleType {

    @XmlEnumValue("AirlineProfile")
    AIRLINE_PROFILE("AirlineProfile"),
    @XmlEnumValue("OrderManagement")
    ORDER_MANAGEMENT("OrderManagement"),
    @XmlEnumValue("PaymentTicketing")
    PAYMENT_TICKETING("PaymentTicketing"),
    @XmlEnumValue("Shopping")
    SHOPPING("Shopping"),
    @XmlEnumValue("Utility")
    UTILITY("Utility");
    private final String value;

    DomainSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DomainSimpleType fromValue(String v) {
        for (DomainSimpleType c: DomainSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
