//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package seatavailability.rq;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketMsgAssocSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="MarketMsgAssocSimpleType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Media"/>
 *     <enumeration value="OfferItem"/>
 *     <enumeration value="Order"/>
 *     <enumeration value="OrderItem"/>
 *     <enumeration value="Payment"/>
 *     <enumeration value="Service"/>
 *     <enumeration value="ServiceBundle"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "MarketMsgAssocSimpleType")
@XmlEnum
public enum MarketMsgAssocSimpleType {

    @XmlEnumValue("Media")
    MEDIA("Media"),
    @XmlEnumValue("OfferItem")
    OFFER_ITEM("OfferItem"),
    @XmlEnumValue("Order")
    ORDER("Order"),
    @XmlEnumValue("OrderItem")
    ORDER_ITEM("OrderItem"),
    @XmlEnumValue("Payment")
    PAYMENT("Payment"),
    @XmlEnumValue("Service")
    SERVICE("Service"),
    @XmlEnumValue("ServiceBundle")
    SERVICE_BUNDLE("ServiceBundle");
    private final String value;

    MarketMsgAssocSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MarketMsgAssocSimpleType fromValue(String v) {
        for (MarketMsgAssocSimpleType c: MarketMsgAssocSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
