//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package orderview.rs;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * CORE ORDER ITEM definition.
 * 
 * <p>Java class for OrderItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="OrderItemType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="OrderItem" maxOccurs="unbounded">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}ItemStatus" minOccurs="0"/>
 *                   <element name="PriceDetail">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="TotalAmount" minOccurs="0">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     <choice>
 *                                       <element ref="{http://www.iata.org/IATA/EDIST/2017.2}AwardPricing"/>
 *                                       <element ref="{http://www.iata.org/IATA/EDIST/2017.2}CombinationPricing"/>
 *                                       <element ref="{http://www.iata.org/IATA/EDIST/2017.2}DetailCurrencyPrice"/>
 *                                       <element ref="{http://www.iata.org/IATA/EDIST/2017.2}EncodedCurrencyPrice"/>
 *                                       <element ref="{http://www.iata.org/IATA/EDIST/2017.2}SimpleCurrencyPrice"/>
 *                                     </choice>
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                             <element name="BaseAmount" type="{http://www.iata.org/IATA/EDIST/2017.2}CurrencyAmountOptType"/>
 *                             <element ref="{http://www.iata.org/IATA/EDIST/2017.2}FareFiledIn" minOccurs="0"/>
 *                             <element name="Discount" type="{http://www.iata.org/IATA/EDIST/2017.2}DiscountType" minOccurs="0"/>
 *                             <element name="Surcharges" minOccurs="0">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     <sequence>
 *                                       <element name="Surcharge" type="{http://www.iata.org/IATA/EDIST/2017.2}FeeSurchargeType" maxOccurs="unbounded"/>
 *                                     </sequence>
 *                                   </restriction>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                             <element name="Taxes" type="{http://www.iata.org/IATA/EDIST/2017.2}TaxDetailType" minOccurs="0"/>
 *                             <element ref="{http://www.iata.org/IATA/EDIST/2017.2}TaxExemption" minOccurs="0"/>
 *                             <choice>
 *                               <element name="AwardPricing" type="{http://www.iata.org/IATA/EDIST/2017.2}AwardPriceUnitType" minOccurs="0"/>
 *                               <element name="CombinationPricing" type="{http://www.iata.org/IATA/EDIST/2017.2}CombinationPriceType" minOccurs="0"/>
 *                             </choice>
 *                             <element name="Fees" minOccurs="0">
 *                               <complexType>
 *                                 <complexContent>
 *                                   <extension base="{http://www.iata.org/IATA/EDIST/2017.2}FeeSurchargeType">
 *                                   </extension>
 *                                 </complexContent>
 *                               </complexType>
 *                             </element>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="Service" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="PassengerRef" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *                             <element name="ServiceRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" minOccurs="0"/>
 *                             <choice>
 *                               <element name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *                               <element name="ServiceDefinitionRef">
 *                                 <complexType>
 *                                   <simpleContent>
 *                                     <extension base="<http://www.w3.org/2001/XMLSchema>IDREF">
 *                                       <attribute name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                                     </extension>
 *                                   </simpleContent>
 *                                 </complexType>
 *                               </element>
 *                               <element name="SelectedSeat">
 *                                 <complexType>
 *                                   <complexContent>
 *                                     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       <sequence>
 *                                         <element name="Seat">
 *                                           <complexType>
 *                                             <complexContent>
 *                                               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 <sequence>
 *                                                   <element name="Row" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                                   <element name="Column" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 </sequence>
 *                                               </restriction>
 *                                             </complexContent>
 *                                           </complexType>
 *                                         </element>
 *                                         <element name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                         <element name="ServiceDefinitionRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       </sequence>
 *                                     </restriction>
 *                                   </complexContent>
 *                                 </complexType>
 *                               </element>
 *                             </choice>
 *                           </sequence>
 *                           <attribute name="ServiceID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           <attribute name="ServiceStatus" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="TimeLimits" type="{http://www.iata.org/IATA/EDIST/2017.2}OrderItemTimeLimitsType" minOccurs="0"/>
 *                   <element name="InventoryGuarantee" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="InventoryGuaranteeID" type="{http://www.iata.org/IATA/EDIST/2017.2}UniqueStringID_SimpleType"/>
 *                             <element ref="{http://www.iata.org/IATA/EDIST/2017.2}InventoryGuaranteeTimeLimits"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}Disclosures" minOccurs="0"/>
 *                   <element name="Penalty" type="{http://www.iata.org/IATA/EDIST/2017.2}OrderPenaltyType" minOccurs="0"/>
 *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}OrderItemDetails" minOccurs="0"/>
 *                   <element name="FareDetail" type="{http://www.iata.org/IATA/EDIST/2017.2}FareDetailType" maxOccurs="unbounded" minOccurs="0"/>
 *                 </sequence>
 *                 <attribute name="OrderItemID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                 <attribute name="Owner" type="{http://www.iata.org/IATA/EDIST/2017.2}AirlineDesigSimpleType" />
 *                 <attribute name="OwnerType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 <attribute name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 <attribute name="WebAddressID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderItemType", propOrder = {
    "orderItem"
})
public class OrderItemType {

    @XmlElement(name = "OrderItem", required = true)
    protected List<OrderItemType.OrderItem> orderItem;

    /**
     * Gets the value of the orderItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the orderItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderItemType.OrderItem }
     * 
     * 
     * @return
     *     The value of the orderItem property.
     */
    public List<OrderItemType.OrderItem> getOrderItem() {
        if (orderItem == null) {
            orderItem = new ArrayList<>();
        }
        return this.orderItem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}ItemStatus" minOccurs="0"/>
     *         <element name="PriceDetail">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="TotalAmount" minOccurs="0">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           <choice>
     *                             <element ref="{http://www.iata.org/IATA/EDIST/2017.2}AwardPricing"/>
     *                             <element ref="{http://www.iata.org/IATA/EDIST/2017.2}CombinationPricing"/>
     *                             <element ref="{http://www.iata.org/IATA/EDIST/2017.2}DetailCurrencyPrice"/>
     *                             <element ref="{http://www.iata.org/IATA/EDIST/2017.2}EncodedCurrencyPrice"/>
     *                             <element ref="{http://www.iata.org/IATA/EDIST/2017.2}SimpleCurrencyPrice"/>
     *                           </choice>
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                   <element name="BaseAmount" type="{http://www.iata.org/IATA/EDIST/2017.2}CurrencyAmountOptType"/>
     *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}FareFiledIn" minOccurs="0"/>
     *                   <element name="Discount" type="{http://www.iata.org/IATA/EDIST/2017.2}DiscountType" minOccurs="0"/>
     *                   <element name="Surcharges" minOccurs="0">
     *                     <complexType>
     *                       <complexContent>
     *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           <sequence>
     *                             <element name="Surcharge" type="{http://www.iata.org/IATA/EDIST/2017.2}FeeSurchargeType" maxOccurs="unbounded"/>
     *                           </sequence>
     *                         </restriction>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                   <element name="Taxes" type="{http://www.iata.org/IATA/EDIST/2017.2}TaxDetailType" minOccurs="0"/>
     *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}TaxExemption" minOccurs="0"/>
     *                   <choice>
     *                     <element name="AwardPricing" type="{http://www.iata.org/IATA/EDIST/2017.2}AwardPriceUnitType" minOccurs="0"/>
     *                     <element name="CombinationPricing" type="{http://www.iata.org/IATA/EDIST/2017.2}CombinationPriceType" minOccurs="0"/>
     *                   </choice>
     *                   <element name="Fees" minOccurs="0">
     *                     <complexType>
     *                       <complexContent>
     *                         <extension base="{http://www.iata.org/IATA/EDIST/2017.2}FeeSurchargeType">
     *                         </extension>
     *                       </complexContent>
     *                     </complexType>
     *                   </element>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="Service" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="PassengerRef" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
     *                   <element name="ServiceRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" minOccurs="0"/>
     *                   <choice>
     *                     <element name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
     *                     <element name="ServiceDefinitionRef">
     *                       <complexType>
     *                         <simpleContent>
     *                           <extension base="<http://www.w3.org/2001/XMLSchema>IDREF">
     *                             <attribute name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *                           </extension>
     *                         </simpleContent>
     *                       </complexType>
     *                     </element>
     *                     <element name="SelectedSeat">
     *                       <complexType>
     *                         <complexContent>
     *                           <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             <sequence>
     *                               <element name="Seat">
     *                                 <complexType>
     *                                   <complexContent>
     *                                     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       <sequence>
     *                                         <element name="Row" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                                         <element name="Column" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       </sequence>
     *                                     </restriction>
     *                                   </complexContent>
     *                                 </complexType>
     *                               </element>
     *                               <element name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                               <element name="ServiceDefinitionRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             </sequence>
     *                           </restriction>
     *                         </complexContent>
     *                       </complexType>
     *                     </element>
     *                   </choice>
     *                 </sequence>
     *                 <attribute name="ServiceID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 <attribute name="ServiceStatus" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="TimeLimits" type="{http://www.iata.org/IATA/EDIST/2017.2}OrderItemTimeLimitsType" minOccurs="0"/>
     *         <element name="InventoryGuarantee" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="InventoryGuaranteeID" type="{http://www.iata.org/IATA/EDIST/2017.2}UniqueStringID_SimpleType"/>
     *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}InventoryGuaranteeTimeLimits"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}Disclosures" minOccurs="0"/>
     *         <element name="Penalty" type="{http://www.iata.org/IATA/EDIST/2017.2}OrderPenaltyType" minOccurs="0"/>
     *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}OrderItemDetails" minOccurs="0"/>
     *         <element name="FareDetail" type="{http://www.iata.org/IATA/EDIST/2017.2}FareDetailType" maxOccurs="unbounded" minOccurs="0"/>
     *       </sequence>
     *       <attribute name="OrderItemID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *       <attribute name="Owner" type="{http://www.iata.org/IATA/EDIST/2017.2}AirlineDesigSimpleType" />
     *       <attribute name="OwnerType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       <attribute name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       <attribute name="WebAddressID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemStatus",
        "priceDetail",
        "service",
        "timeLimits",
        "inventoryGuarantee",
        "disclosures",
        "penalty",
        "orderItemDetails",
        "fareDetail"
    })
    public static class OrderItem {

        @XmlElement(name = "ItemStatus")
        protected String itemStatus;
        @XmlElement(name = "PriceDetail", required = true)
        protected OrderItemType.OrderItem.PriceDetail priceDetail;
        @XmlElement(name = "Service", required = true)
        protected List<OrderItemType.OrderItem.Service> service;
        @XmlElement(name = "TimeLimits")
        protected OrderItemTimeLimitsType timeLimits;
        @XmlElement(name = "InventoryGuarantee")
        protected OrderItemType.OrderItem.InventoryGuarantee inventoryGuarantee;
        @XmlElement(name = "Disclosures")
        protected Disclosures disclosures;
        @XmlElement(name = "Penalty")
        protected OrderPenaltyType penalty;
        @XmlElement(name = "OrderItemDetails")
        protected OrderItemDetails orderItemDetails;
        @XmlElement(name = "FareDetail")
        protected List<FareDetailType> fareDetail;
        @XmlAttribute(name = "OrderItemID", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String orderItemID;
        @XmlAttribute(name = "Owner")
        protected String owner;
        @XmlAttribute(name = "OwnerType")
        protected String ownerType;
        @XmlAttribute(name = "Timestamp")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timestamp;
        @XmlAttribute(name = "WebAddressID")
        protected String webAddressID;

        /**
         * Current Order Item status. Example: OK (Confirmed) Encoding Scheme: IATA Padis Codeset - List for data element 4405 (Status, coded)
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemStatus() {
            return itemStatus;
        }

        /**
         * Sets the value of the itemStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemStatus(String value) {
            this.itemStatus = value;
        }

        /**
         * Gets the value of the priceDetail property.
         * 
         * @return
         *     possible object is
         *     {@link OrderItemType.OrderItem.PriceDetail }
         *     
         */
        public OrderItemType.OrderItem.PriceDetail getPriceDetail() {
            return priceDetail;
        }

        /**
         * Sets the value of the priceDetail property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrderItemType.OrderItem.PriceDetail }
         *     
         */
        public void setPriceDetail(OrderItemType.OrderItem.PriceDetail value) {
            this.priceDetail = value;
        }

        /**
         * Gets the value of the service property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the service property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getService().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrderItemType.OrderItem.Service }
         * 
         * 
         * @return
         *     The value of the service property.
         */
        public List<OrderItemType.OrderItem.Service> getService() {
            if (service == null) {
                service = new ArrayList<>();
            }
            return this.service;
        }

        /**
         * Gets the value of the timeLimits property.
         * 
         * @return
         *     possible object is
         *     {@link OrderItemTimeLimitsType }
         *     
         */
        public OrderItemTimeLimitsType getTimeLimits() {
            return timeLimits;
        }

        /**
         * Sets the value of the timeLimits property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrderItemTimeLimitsType }
         *     
         */
        public void setTimeLimits(OrderItemTimeLimitsType value) {
            this.timeLimits = value;
        }

        /**
         * Gets the value of the inventoryGuarantee property.
         * 
         * @return
         *     possible object is
         *     {@link OrderItemType.OrderItem.InventoryGuarantee }
         *     
         */
        public OrderItemType.OrderItem.InventoryGuarantee getInventoryGuarantee() {
            return inventoryGuarantee;
        }

        /**
         * Sets the value of the inventoryGuarantee property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrderItemType.OrderItem.InventoryGuarantee }
         *     
         */
        public void setInventoryGuarantee(OrderItemType.OrderItem.InventoryGuarantee value) {
            this.inventoryGuarantee = value;
        }

        /**
         * Gets the value of the disclosures property.
         * 
         * @return
         *     possible object is
         *     {@link Disclosures }
         *     
         */
        public Disclosures getDisclosures() {
            return disclosures;
        }

        /**
         * Sets the value of the disclosures property.
         * 
         * @param value
         *     allowed object is
         *     {@link Disclosures }
         *     
         */
        public void setDisclosures(Disclosures value) {
            this.disclosures = value;
        }

        /**
         * Gets the value of the penalty property.
         * 
         * @return
         *     possible object is
         *     {@link OrderPenaltyType }
         *     
         */
        public OrderPenaltyType getPenalty() {
            return penalty;
        }

        /**
         * Sets the value of the penalty property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrderPenaltyType }
         *     
         */
        public void setPenalty(OrderPenaltyType value) {
            this.penalty = value;
        }

        /**
         * Gets the value of the orderItemDetails property.
         * 
         * @return
         *     possible object is
         *     {@link OrderItemDetails }
         *     
         */
        public OrderItemDetails getOrderItemDetails() {
            return orderItemDetails;
        }

        /**
         * Sets the value of the orderItemDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrderItemDetails }
         *     
         */
        public void setOrderItemDetails(OrderItemDetails value) {
            this.orderItemDetails = value;
        }

        /**
         * Gets the value of the fareDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a {@code set} method for the fareDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFareDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FareDetailType }
         * 
         * 
         * @return
         *     The value of the fareDetail property.
         */
        public List<FareDetailType> getFareDetail() {
            if (fareDetail == null) {
                fareDetail = new ArrayList<>();
            }
            return this.fareDetail;
        }

        /**
         * Gets the value of the orderItemID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderItemID() {
            return orderItemID;
        }

        /**
         * Sets the value of the orderItemID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderItemID(String value) {
            this.orderItemID = value;
        }

        /**
         * Gets the value of the owner property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOwner() {
            return owner;
        }

        /**
         * Sets the value of the owner property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOwner(String value) {
            this.owner = value;
        }

        /**
         * Gets the value of the ownerType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOwnerType() {
            return ownerType;
        }

        /**
         * Sets the value of the ownerType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOwnerType(String value) {
            this.ownerType = value;
        }

        /**
         * Gets the value of the timestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimestamp() {
            return timestamp;
        }

        /**
         * Sets the value of the timestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimestamp(XMLGregorianCalendar value) {
            this.timestamp = value;
        }

        /**
         * Gets the value of the webAddressID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWebAddressID() {
            return webAddressID;
        }

        /**
         * Sets the value of the webAddressID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWebAddressID(String value) {
            this.webAddressID = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="InventoryGuaranteeID" type="{http://www.iata.org/IATA/EDIST/2017.2}UniqueStringID_SimpleType"/>
         *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}InventoryGuaranteeTimeLimits"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "inventoryGuaranteeID",
            "inventoryGuaranteeTimeLimits"
        })
        public static class InventoryGuarantee {

            @XmlElement(name = "InventoryGuaranteeID", required = true)
            protected String inventoryGuaranteeID;
            @XmlElement(name = "InventoryGuaranteeTimeLimits", required = true)
            protected InventoryGuaranteeTimeLimits inventoryGuaranteeTimeLimits;

            /**
             * Gets the value of the inventoryGuaranteeID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInventoryGuaranteeID() {
                return inventoryGuaranteeID;
            }

            /**
             * Sets the value of the inventoryGuaranteeID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInventoryGuaranteeID(String value) {
                this.inventoryGuaranteeID = value;
            }

            /**
             * Gets the value of the inventoryGuaranteeTimeLimits property.
             * 
             * @return
             *     possible object is
             *     {@link InventoryGuaranteeTimeLimits }
             *     
             */
            public InventoryGuaranteeTimeLimits getInventoryGuaranteeTimeLimits() {
                return inventoryGuaranteeTimeLimits;
            }

            /**
             * Sets the value of the inventoryGuaranteeTimeLimits property.
             * 
             * @param value
             *     allowed object is
             *     {@link InventoryGuaranteeTimeLimits }
             *     
             */
            public void setInventoryGuaranteeTimeLimits(InventoryGuaranteeTimeLimits value) {
                this.inventoryGuaranteeTimeLimits = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="TotalAmount" minOccurs="0">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 <choice>
         *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}AwardPricing"/>
         *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}CombinationPricing"/>
         *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}DetailCurrencyPrice"/>
         *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}EncodedCurrencyPrice"/>
         *                   <element ref="{http://www.iata.org/IATA/EDIST/2017.2}SimpleCurrencyPrice"/>
         *                 </choice>
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *         <element name="BaseAmount" type="{http://www.iata.org/IATA/EDIST/2017.2}CurrencyAmountOptType"/>
         *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}FareFiledIn" minOccurs="0"/>
         *         <element name="Discount" type="{http://www.iata.org/IATA/EDIST/2017.2}DiscountType" minOccurs="0"/>
         *         <element name="Surcharges" minOccurs="0">
         *           <complexType>
         *             <complexContent>
         *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 <sequence>
         *                   <element name="Surcharge" type="{http://www.iata.org/IATA/EDIST/2017.2}FeeSurchargeType" maxOccurs="unbounded"/>
         *                 </sequence>
         *               </restriction>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *         <element name="Taxes" type="{http://www.iata.org/IATA/EDIST/2017.2}TaxDetailType" minOccurs="0"/>
         *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}TaxExemption" minOccurs="0"/>
         *         <choice>
         *           <element name="AwardPricing" type="{http://www.iata.org/IATA/EDIST/2017.2}AwardPriceUnitType" minOccurs="0"/>
         *           <element name="CombinationPricing" type="{http://www.iata.org/IATA/EDIST/2017.2}CombinationPriceType" minOccurs="0"/>
         *         </choice>
         *         <element name="Fees" minOccurs="0">
         *           <complexType>
         *             <complexContent>
         *               <extension base="{http://www.iata.org/IATA/EDIST/2017.2}FeeSurchargeType">
         *               </extension>
         *             </complexContent>
         *           </complexType>
         *         </element>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "totalAmount",
            "baseAmount",
            "fareFiledIn",
            "discount",
            "surcharges",
            "taxes",
            "taxExemption",
            "awardPricing",
            "combinationPricing",
            "fees"
        })
        public static class PriceDetail {

            @XmlElement(name = "TotalAmount")
            protected OrderItemType.OrderItem.PriceDetail.TotalAmount totalAmount;
            @XmlElement(name = "BaseAmount", required = true)
            protected CurrencyAmountOptType baseAmount;
            @XmlElement(name = "FareFiledIn")
            protected FareFilingType fareFiledIn;
            @XmlElement(name = "Discount")
            protected DiscountType discount;
            @XmlElement(name = "Surcharges")
            protected OrderItemType.OrderItem.PriceDetail.Surcharges surcharges;
            @XmlElement(name = "Taxes")
            protected TaxDetailType taxes;
            @XmlElement(name = "TaxExemption")
            protected TaxExemptionType taxExemption;
            @XmlElement(name = "AwardPricing")
            protected AwardPriceUnitType awardPricing;
            @XmlElement(name = "CombinationPricing")
            protected CombinationPriceType combinationPricing;
            @XmlElement(name = "Fees")
            protected OrderItemType.OrderItem.PriceDetail.Fees fees;

            /**
             * Gets the value of the totalAmount property.
             * 
             * @return
             *     possible object is
             *     {@link OrderItemType.OrderItem.PriceDetail.TotalAmount }
             *     
             */
            public OrderItemType.OrderItem.PriceDetail.TotalAmount getTotalAmount() {
                return totalAmount;
            }

            /**
             * Sets the value of the totalAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link OrderItemType.OrderItem.PriceDetail.TotalAmount }
             *     
             */
            public void setTotalAmount(OrderItemType.OrderItem.PriceDetail.TotalAmount value) {
                this.totalAmount = value;
            }

            /**
             * Gets the value of the baseAmount property.
             * 
             * @return
             *     possible object is
             *     {@link CurrencyAmountOptType }
             *     
             */
            public CurrencyAmountOptType getBaseAmount() {
                return baseAmount;
            }

            /**
             * Sets the value of the baseAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link CurrencyAmountOptType }
             *     
             */
            public void setBaseAmount(CurrencyAmountOptType value) {
                this.baseAmount = value;
            }

            /**
             * Gets the value of the fareFiledIn property.
             * 
             * @return
             *     possible object is
             *     {@link FareFilingType }
             *     
             */
            public FareFilingType getFareFiledIn() {
                return fareFiledIn;
            }

            /**
             * Sets the value of the fareFiledIn property.
             * 
             * @param value
             *     allowed object is
             *     {@link FareFilingType }
             *     
             */
            public void setFareFiledIn(FareFilingType value) {
                this.fareFiledIn = value;
            }

            /**
             * Gets the value of the discount property.
             * 
             * @return
             *     possible object is
             *     {@link DiscountType }
             *     
             */
            public DiscountType getDiscount() {
                return discount;
            }

            /**
             * Sets the value of the discount property.
             * 
             * @param value
             *     allowed object is
             *     {@link DiscountType }
             *     
             */
            public void setDiscount(DiscountType value) {
                this.discount = value;
            }

            /**
             * Gets the value of the surcharges property.
             * 
             * @return
             *     possible object is
             *     {@link OrderItemType.OrderItem.PriceDetail.Surcharges }
             *     
             */
            public OrderItemType.OrderItem.PriceDetail.Surcharges getSurcharges() {
                return surcharges;
            }

            /**
             * Sets the value of the surcharges property.
             * 
             * @param value
             *     allowed object is
             *     {@link OrderItemType.OrderItem.PriceDetail.Surcharges }
             *     
             */
            public void setSurcharges(OrderItemType.OrderItem.PriceDetail.Surcharges value) {
                this.surcharges = value;
            }

            /**
             * Gets the value of the taxes property.
             * 
             * @return
             *     possible object is
             *     {@link TaxDetailType }
             *     
             */
            public TaxDetailType getTaxes() {
                return taxes;
            }

            /**
             * Sets the value of the taxes property.
             * 
             * @param value
             *     allowed object is
             *     {@link TaxDetailType }
             *     
             */
            public void setTaxes(TaxDetailType value) {
                this.taxes = value;
            }

            /**
             * Gets the value of the taxExemption property.
             * 
             * @return
             *     possible object is
             *     {@link TaxExemptionType }
             *     
             */
            public TaxExemptionType getTaxExemption() {
                return taxExemption;
            }

            /**
             * Sets the value of the taxExemption property.
             * 
             * @param value
             *     allowed object is
             *     {@link TaxExemptionType }
             *     
             */
            public void setTaxExemption(TaxExemptionType value) {
                this.taxExemption = value;
            }

            /**
             * Gets the value of the awardPricing property.
             * 
             * @return
             *     possible object is
             *     {@link AwardPriceUnitType }
             *     
             */
            public AwardPriceUnitType getAwardPricing() {
                return awardPricing;
            }

            /**
             * Sets the value of the awardPricing property.
             * 
             * @param value
             *     allowed object is
             *     {@link AwardPriceUnitType }
             *     
             */
            public void setAwardPricing(AwardPriceUnitType value) {
                this.awardPricing = value;
            }

            /**
             * Gets the value of the combinationPricing property.
             * 
             * @return
             *     possible object is
             *     {@link CombinationPriceType }
             *     
             */
            public CombinationPriceType getCombinationPricing() {
                return combinationPricing;
            }

            /**
             * Sets the value of the combinationPricing property.
             * 
             * @param value
             *     allowed object is
             *     {@link CombinationPriceType }
             *     
             */
            public void setCombinationPricing(CombinationPriceType value) {
                this.combinationPricing = value;
            }

            /**
             * Gets the value of the fees property.
             * 
             * @return
             *     possible object is
             *     {@link OrderItemType.OrderItem.PriceDetail.Fees }
             *     
             */
            public OrderItemType.OrderItem.PriceDetail.Fees getFees() {
                return fees;
            }

            /**
             * Sets the value of the fees property.
             * 
             * @param value
             *     allowed object is
             *     {@link OrderItemType.OrderItem.PriceDetail.Fees }
             *     
             */
            public void setFees(OrderItemType.OrderItem.PriceDetail.Fees value) {
                this.fees = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <extension base="{http://www.iata.org/IATA/EDIST/2017.2}FeeSurchargeType">
             *     </extension>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Fees
                extends FeeSurchargeType
            {


            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       <sequence>
             *         <element name="Surcharge" type="{http://www.iata.org/IATA/EDIST/2017.2}FeeSurchargeType" maxOccurs="unbounded"/>
             *       </sequence>
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "surcharge"
            })
            public static class Surcharges {

                @XmlElement(name = "Surcharge", required = true)
                protected List<FeeSurchargeType> surcharge;

                /**
                 * Gets the value of the surcharge property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a {@code set} method for the surcharge property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getSurcharge().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link FeeSurchargeType }
                 * 
                 * 
                 * @return
                 *     The value of the surcharge property.
                 */
                public List<FeeSurchargeType> getSurcharge() {
                    if (surcharge == null) {
                        surcharge = new ArrayList<>();
                    }
                    return this.surcharge;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       <choice>
             *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}AwardPricing"/>
             *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}CombinationPricing"/>
             *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}DetailCurrencyPrice"/>
             *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}EncodedCurrencyPrice"/>
             *         <element ref="{http://www.iata.org/IATA/EDIST/2017.2}SimpleCurrencyPrice"/>
             *       </choice>
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "awardPricing",
                "combinationPricing",
                "detailCurrencyPrice",
                "encodedCurrencyPrice",
                "simpleCurrencyPrice"
            })
            public static class TotalAmount {

                @XmlElement(name = "AwardPricing")
                protected AwardPriceUnitType awardPricing;
                @XmlElement(name = "CombinationPricing")
                protected CombinationPriceType combinationPricing;
                @XmlElement(name = "DetailCurrencyPrice")
                protected DetailCurrencyPriceType detailCurrencyPrice;
                @XmlElement(name = "EncodedCurrencyPrice")
                protected EncodedPriceType encodedCurrencyPrice;
                @XmlElement(name = "SimpleCurrencyPrice")
                protected SimpleCurrencyPriceType simpleCurrencyPrice;

                /**
                 * Gets the value of the awardPricing property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link AwardPriceUnitType }
                 *     
                 */
                public AwardPriceUnitType getAwardPricing() {
                    return awardPricing;
                }

                /**
                 * Sets the value of the awardPricing property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link AwardPriceUnitType }
                 *     
                 */
                public void setAwardPricing(AwardPriceUnitType value) {
                    this.awardPricing = value;
                }

                /**
                 * Gets the value of the combinationPricing property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link CombinationPriceType }
                 *     
                 */
                public CombinationPriceType getCombinationPricing() {
                    return combinationPricing;
                }

                /**
                 * Sets the value of the combinationPricing property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link CombinationPriceType }
                 *     
                 */
                public void setCombinationPricing(CombinationPriceType value) {
                    this.combinationPricing = value;
                }

                /**
                 * Gets the value of the detailCurrencyPrice property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DetailCurrencyPriceType }
                 *     
                 */
                public DetailCurrencyPriceType getDetailCurrencyPrice() {
                    return detailCurrencyPrice;
                }

                /**
                 * Sets the value of the detailCurrencyPrice property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DetailCurrencyPriceType }
                 *     
                 */
                public void setDetailCurrencyPrice(DetailCurrencyPriceType value) {
                    this.detailCurrencyPrice = value;
                }

                /**
                 * Gets the value of the encodedCurrencyPrice property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link EncodedPriceType }
                 *     
                 */
                public EncodedPriceType getEncodedCurrencyPrice() {
                    return encodedCurrencyPrice;
                }

                /**
                 * Sets the value of the encodedCurrencyPrice property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link EncodedPriceType }
                 *     
                 */
                public void setEncodedCurrencyPrice(EncodedPriceType value) {
                    this.encodedCurrencyPrice = value;
                }

                /**
                 * Gets the value of the simpleCurrencyPrice property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link SimpleCurrencyPriceType }
                 *     
                 */
                public SimpleCurrencyPriceType getSimpleCurrencyPrice() {
                    return simpleCurrencyPrice;
                }

                /**
                 * Sets the value of the simpleCurrencyPrice property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link SimpleCurrencyPriceType }
                 *     
                 */
                public void setSimpleCurrencyPrice(SimpleCurrencyPriceType value) {
                    this.simpleCurrencyPrice = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="PassengerRef" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
         *         <element name="ServiceRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" minOccurs="0"/>
         *         <choice>
         *           <element name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
         *           <element name="ServiceDefinitionRef">
         *             <complexType>
         *               <simpleContent>
         *                 <extension base="<http://www.w3.org/2001/XMLSchema>IDREF">
         *                   <attribute name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
         *                 </extension>
         *               </simpleContent>
         *             </complexType>
         *           </element>
         *           <element name="SelectedSeat">
         *             <complexType>
         *               <complexContent>
         *                 <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   <sequence>
         *                     <element name="Seat">
         *                       <complexType>
         *                         <complexContent>
         *                           <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             <sequence>
         *                               <element name="Row" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                               <element name="Column" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             </sequence>
         *                           </restriction>
         *                         </complexContent>
         *                       </complexType>
         *                     </element>
         *                     <element name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                     <element name="ServiceDefinitionRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   </sequence>
         *                 </restriction>
         *               </complexContent>
         *             </complexType>
         *           </element>
         *         </choice>
         *       </sequence>
         *       <attribute name="ServiceID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       <attribute name="ServiceStatus" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "passengerRef",
            "serviceRef",
            "segmentRef",
            "serviceDefinitionRef",
            "selectedSeat"
        })
        public static class Service {

            @XmlElement(name = "PassengerRef", required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object passengerRef;
            @XmlElement(name = "ServiceRef")
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object serviceRef;
            @XmlElement(name = "SegmentRef")
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object segmentRef;
            @XmlElement(name = "ServiceDefinitionRef")
            protected OrderItemType.OrderItem.Service.ServiceDefinitionRef serviceDefinitionRef;
            @XmlElement(name = "SelectedSeat")
            protected OrderItemType.OrderItem.Service.SelectedSeat selectedSeat;
            @XmlAttribute(name = "ServiceID", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String serviceID;
            @XmlAttribute(name = "ServiceStatus")
            @XmlSchemaType(name = "anySimpleType")
            protected String serviceStatus;

            /**
             * Gets the value of the passengerRef property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getPassengerRef() {
                return passengerRef;
            }

            /**
             * Sets the value of the passengerRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setPassengerRef(Object value) {
                this.passengerRef = value;
            }

            /**
             * Gets the value of the serviceRef property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getServiceRef() {
                return serviceRef;
            }

            /**
             * Sets the value of the serviceRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setServiceRef(Object value) {
                this.serviceRef = value;
            }

            /**
             * Gets the value of the segmentRef property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getSegmentRef() {
                return segmentRef;
            }

            /**
             * Sets the value of the segmentRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setSegmentRef(Object value) {
                this.segmentRef = value;
            }

            /**
             * Gets the value of the serviceDefinitionRef property.
             * 
             * @return
             *     possible object is
             *     {@link OrderItemType.OrderItem.Service.ServiceDefinitionRef }
             *     
             */
            public OrderItemType.OrderItem.Service.ServiceDefinitionRef getServiceDefinitionRef() {
                return serviceDefinitionRef;
            }

            /**
             * Sets the value of the serviceDefinitionRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link OrderItemType.OrderItem.Service.ServiceDefinitionRef }
             *     
             */
            public void setServiceDefinitionRef(OrderItemType.OrderItem.Service.ServiceDefinitionRef value) {
                this.serviceDefinitionRef = value;
            }

            /**
             * Gets the value of the selectedSeat property.
             * 
             * @return
             *     possible object is
             *     {@link OrderItemType.OrderItem.Service.SelectedSeat }
             *     
             */
            public OrderItemType.OrderItem.Service.SelectedSeat getSelectedSeat() {
                return selectedSeat;
            }

            /**
             * Sets the value of the selectedSeat property.
             * 
             * @param value
             *     allowed object is
             *     {@link OrderItemType.OrderItem.Service.SelectedSeat }
             *     
             */
            public void setSelectedSeat(OrderItemType.OrderItem.Service.SelectedSeat value) {
                this.selectedSeat = value;
            }

            /**
             * Gets the value of the serviceID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceID() {
                return serviceID;
            }

            /**
             * Sets the value of the serviceID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceID(String value) {
                this.serviceID = value;
            }

            /**
             * Gets the value of the serviceStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceStatus() {
                return serviceStatus;
            }

            /**
             * Sets the value of the serviceStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceStatus(String value) {
                this.serviceStatus = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <complexContent>
             *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       <sequence>
             *         <element name="Seat">
             *           <complexType>
             *             <complexContent>
             *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 <sequence>
             *                   <element name="Row" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *                   <element name="Column" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 </sequence>
             *               </restriction>
             *             </complexContent>
             *           </complexType>
             *         </element>
             *         <element name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         <element name="ServiceDefinitionRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       </sequence>
             *     </restriction>
             *   </complexContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "seat",
                "segmentRef",
                "serviceDefinitionRef"
            })
            public static class SelectedSeat {

                @XmlElement(name = "Seat", required = true)
                protected OrderItemType.OrderItem.Service.SelectedSeat.Seat seat;
                @XmlElement(name = "SegmentRef", required = true)
                protected Object segmentRef;
                @XmlElement(name = "ServiceDefinitionRef", required = true)
                protected Object serviceDefinitionRef;

                /**
                 * Gets the value of the seat property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link OrderItemType.OrderItem.Service.SelectedSeat.Seat }
                 *     
                 */
                public OrderItemType.OrderItem.Service.SelectedSeat.Seat getSeat() {
                    return seat;
                }

                /**
                 * Sets the value of the seat property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link OrderItemType.OrderItem.Service.SelectedSeat.Seat }
                 *     
                 */
                public void setSeat(OrderItemType.OrderItem.Service.SelectedSeat.Seat value) {
                    this.seat = value;
                }

                /**
                 * Gets the value of the segmentRef property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getSegmentRef() {
                    return segmentRef;
                }

                /**
                 * Sets the value of the segmentRef property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setSegmentRef(Object value) {
                    this.segmentRef = value;
                }

                /**
                 * Gets the value of the serviceDefinitionRef property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getServiceDefinitionRef() {
                    return serviceDefinitionRef;
                }

                /**
                 * Sets the value of the serviceDefinitionRef property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setServiceDefinitionRef(Object value) {
                    this.serviceDefinitionRef = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>{@code
                 * <complexType>
                 *   <complexContent>
                 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       <sequence>
                 *         <element name="Row" type="{http://www.w3.org/2001/XMLSchema}integer"/>
                 *         <element name="Column" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       </sequence>
                 *     </restriction>
                 *   </complexContent>
                 * </complexType>
                 * }</pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "row",
                    "column"
                })
                public static class Seat {

                    @XmlElement(name = "Row", required = true)
                    protected BigInteger row;
                    @XmlElement(name = "Column", required = true)
                    protected String column;

                    /**
                     * Gets the value of the row property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getRow() {
                        return row;
                    }

                    /**
                     * Sets the value of the row property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setRow(BigInteger value) {
                        this.row = value;
                    }

                    /**
                     * Gets the value of the column property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getColumn() {
                        return column;
                    }

                    /**
                     * Sets the value of the column property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setColumn(String value) {
                        this.column = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>{@code
             * <complexType>
             *   <simpleContent>
             *     <extension base="<http://www.w3.org/2001/XMLSchema>IDREF">
             *       <attribute name="SegmentRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
             *     </extension>
             *   </simpleContent>
             * </complexType>
             * }</pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class ServiceDefinitionRef {

                @XmlValue
                @XmlIDREF
                @XmlSchemaType(name = "IDREF")
                protected Object value;
                @XmlAttribute(name = "SegmentRef")
                @XmlIDREF
                @XmlSchemaType(name = "IDREF")
                protected Object segmentRef;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setValue(Object value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the segmentRef property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getSegmentRef() {
                    return segmentRef;
                }

                /**
                 * Sets the value of the segmentRef property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setSegmentRef(Object value) {
                    this.segmentRef = value;
                }

            }

        }

    }

}
